[project]
name = "blogging-api-roadmapsh"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi>=0.115.5",
    "psycopg2>=2.9.10",
    "uvicorn>=0.32.0",
]
